# Generated by Django 4.1.11 on 2023-09-15 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='employee.department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='employee_resumes/'),
        ),
    ]
