# Exclude markdown files and the config itself from pre-commit hooks
exclude: '\.(md|yaml)$'

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-json
    -   id: check-merge-conflict
    -   id: detect-private-key

# Ruff for fast linting and auto-fixing
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.3
    hooks:
    -   id: ruff
    -   id: ruff-format 