[tool.ruff]
line-length = 120

extend-exclude = []

[tool.ruff.lint]
select = [
    "E", # Pycodestyle
    "F", # Pyflakes
    "W", # Pycodestyle
    "B", # Bugbear
    "C90", # McCabe complexity
    "I", # isort
    "DJ", # Django
    "PT", # Pytest style
    "C4", # Comprehensions
    "ARG", # Unused arguments
    "SIM", # Simplify
    "PLE", # Pylint errors
    "PLR", # Pylint refactor
    "PLW", # Pylint warning
    ]

ignore = []
