# Generated by Django 4.1.11 on 2023-09-15 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='project',
            name='employees',
        ),
        migrations.RemoveField(
            model_name='projectemployee',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='projectemployee',
            name='project',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectEmployee',
        ),
    ]
