# Generated by Django 4.1.11 on 2023-09-12 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employee_contact_employee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('employees', models.ManyToManyField(related_name='projects_involved', to='core.employee')),
            ],
        ),
    ]
