version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=false  # Disable development dependencies for production
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - dev-static-data:/vol/web/static
      - ./public:/public
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             gunicorn -c /gunicorn_config.py app.wsgi:application"
    environment:
      - DB_HOST=db
      - DB_NAME=prod_db
      - DB_USER=prod_user
      - DB_PASS=prod_password
      - DEBUG=0
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13-alpine
    volumes:
      - prod-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=prod_db
      - POSTGRES_USER=prod_user
      - POSTGRES_PASSWORD=prod_password
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "prod_db", "-U", "prod_user"]

volumes:
  prod-db-data:
  dev-static-data:  # Define a volume for static files
